# This file configures the analyzer to use the lint rule set from `package:lint`
# Install dev dependency:
# flutter pub add --dev lint

include: package:lint/strict.yaml # For production apps
# include: package:lint/casual.yaml # For code samples, hackathons and other non-production code
# include: package:lint/package.yaml # Use this for packages with public API

analyzer:
  exclude:
    - "**.freezed.dart"
    - "**.g.dart"
    - "**.gen.dart"
    - "**/*.mocks.dart"
  language:
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    # ---- STYLE ----
    prefer_double_quotes: error
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    avoid_print: true
    always_put_required_named_parameters_first: true
    require_trailing_commas: true

    # ---- SAFETY ----
    avoid_dynamic_calls: true
    avoid_returning_null: true
    avoid_returning_null_for_future: true
    avoid_returning_null_for_void: true
    avoid_unused_constructor_parameters: true
    cancel_subscriptions: true
    close_sinks: true
    unawaited_futures: true

    # ---- BEST PRACTICES ----
    avoid_bool_literals_in_conditional_expressions: true
    avoid_function_literals_in_foreach_calls: true
    avoid_init_to_null: true
    avoid_positional_boolean_parameters: true
    cascade_invocations: true
    directives_ordering: true
    literal_only_boolean_expressions: true
    no_adjacent_strings_in_list: true
    prefer_final_fields: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    prefer_single_quotes: false
    use_full_hex_values_for_flutter_colors: true
    use_key_in_widget_constructors: true

    # ---- DOCUMENTATION ----
    comment_references: true
