// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_aqsLnU526od-TJ62oF31bKfWntLvN8g',
    appId: '1:677481332114:web:256a8768b51e6822b1954b',
    messagingSenderId: '677481332114',
    projectId: 'petpass-c7944',
    authDomain: 'petpass-c7944.firebaseapp.com',
    storageBucket: 'petpass-c7944.firebasestorage.app',
    measurementId: 'G-29L7YKXPEB',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChib_RAORdQyQxE2gzmifzu2JOdo7y4xI',
    appId: '1:677481332114:ios:88e094cf51d9ab7bb1954b',
    messagingSenderId: '677481332114',
    projectId: 'petpass-c7944',
    storageBucket: 'petpass-c7944.firebasestorage.app',
    iosBundleId: 'com.example.petpass',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_aqsLnU526od-TJ62oF31bKfWntLvN8g',
    appId: '1:677481332114:web:9bd37e9703613839b1954b',
    messagingSenderId: '677481332114',
    projectId: 'petpass-c7944',
    authDomain: 'petpass-c7944.firebaseapp.com',
    storageBucket: 'petpass-c7944.firebasestorage.app',
    measurementId: 'G-JQRKW4EBY2',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChib_RAORdQyQxE2gzmifzu2JOdo7y4xI',
    appId: '1:677481332114:ios:88e094cf51d9ab7bb1954b',
    messagingSenderId: '677481332114',
    projectId: 'petpass-c7944',
    storageBucket: 'petpass-c7944.firebasestorage.app',
    iosBundleId: 'com.example.petpass',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRpxg3c8t9OEIXHxMTH_Wgz2tXPdE_ufk',
    appId: '1:677481332114:android:3c1bf62b72e0e6ebb1954b',
    messagingSenderId: '677481332114',
    projectId: 'petpass-c7944',
    storageBucket: 'petpass-c7944.firebasestorage.app',
  );

}