// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnSDIp8nazIhmOMziWsgZsFBKDAyqppxQ',
    appId: '1:904564507964:web:0218374b1f69458a430a39',
    messagingSenderId: '904564507964',
    projectId: 'petpass-c14',
    authDomain: 'petpass-c14.firebaseapp.com',
    storageBucket: 'petpass-c14.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHZ-rIWzYo-4CP8h66eT_M7H3DbcuV9vg',
    appId: '1:904564507964:ios:ca0acdf6a14d4423430a39',
    messagingSenderId: '904564507964',
    projectId: 'petpass-c14',
    storageBucket: 'petpass-c14.firebasestorage.app',
    iosBundleId: 'com.example.petpass',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnSDIp8nazIhmOMziWsgZsFBKDAyqppxQ',
    appId: '1:904564507964:web:e8f06cee3f64d4ef430a39',
    messagingSenderId: '904564507964',
    projectId: 'petpass-c14',
    authDomain: 'petpass-c14.firebaseapp.com',
    storageBucket: 'petpass-c14.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHZ-rIWzYo-4CP8h66eT_M7H3DbcuV9vg',
    appId: '1:904564507964:ios:ca0acdf6a14d4423430a39',
    messagingSenderId: '904564507964',
    projectId: 'petpass-c14',
    storageBucket: 'petpass-c14.firebasestorage.app',
    iosBundleId: 'com.example.petpass',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7IuCZWZ4YswNS6cp2WdaZB2Q043waezI',
    appId: '1:904564507964:android:ffe72ff19f6a01dc430a39',
    messagingSenderId: '904564507964',
    projectId: 'petpass-c14',
    storageBucket: 'petpass-c14.firebasestorage.app',
  );

}